openapi: 3.0.1
info:
  title: Todo App
  description: Todo App Swagger Documentation
  version: '0.1'
servers:
  - url: 'https://fullstack-todo-app-server.herokuapp.com'
paths:
  /todos:
    description: Todos
    get:
      description: Get All Todos
      responses:
        '200':
          description: All Todos have been succesfully fetched.
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}  
  /todos/:id:
    get:
      description: Get specific Todo by id.
      responses:
        '200':
          description: Specific Todo is succesfully fetched.
          
    put:
      description: Edit/Update specific Todo by id.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                author:
                  type: string
                text:
                  type: string
                title:
                  type: string
                userid:
                  type: string
            examples:
              '0':
                value: |-
                  {
                      "title": "123",
                      "text": "t1231",
                      "author": "mert",
                      "userid": "2"
                  }
      responses:
        '200':
          description: Todo Succesfully updated.
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}
    
    delete:
      description: Delete specific Todo by its id.
      responses:
        '200':
          description: Todo is deleted by its id successfully.
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}
      
  /todos/add:
    post:
      description: Create/Add Todo.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                title:
                  type: string
                userId:
                  type: integer
            examples:
              '0':
                value: |-
                  {
                      "title": "123",
                      "text": "t1231",
                      "userId": 12
                  }
      responses:
        '200':
          description: Todo Successfully created.
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}